version: '3'

services:
  api:
    image: vinculos_servicie:0.3
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vinculos_service
    ports:
        - "5437:5432"
#    volumes:
#        - ./teleconsultoria_producao_2023-11-13.sql:/docker-entrypoint-initdb.d/teleconsultoria_producao_2023-11-13.sql
    restart: unless-stopped