version: '3'

services:
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vinculos_service
    ports:
        - "5437:5432"
#    volumes:
#        - ./teleconsultoria_producao_2023-11-13.sql:/docker-entrypoint-initdb.d/teleconsultoria_producao_2023-11-13.sql
    restart: unless-stopped