# Generated by Django 5.0.1 on 2024-02-20 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cns', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=7)),
                ('cbo', models.CharField(max_length=100)),
                ('cnes', models.CharField(max_length=7)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.profissional')),
            ],
        ),
    ]
