# Generated by Django 5.0.1 on 2024-01-09 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cns', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=7)),
                ('ibge', models.CharField(max_length=7)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=50)),
                ('cbo', models.CharField(max_length=100)),
                ('cnes', models.CharField(max_length=7)),
                ('cnpj', models.CharField(max_length=14)),
                ('estabelecimento', models.CharField(max_length=100)),
                ('nat_juridica', models.CharField(max_length=100)),
                ('gestao', models.CharField(max_length=1)),
                ('sus', models.CharField(max_length=3)),
                ('vinculo_estabelecimento', models.CharField(max_length=100)),
                ('vinculo_empregador', models.CharField(max_length=100)),
                ('detalhamento_vinculo', models.CharField(max_length=100)),
                ('ch_outros', models.IntegerField(blank=True, null=True)),
                ('ch_ambulatorial', models.IntegerField(blank=True, null=True)),
                ('ch_hospitalar', models.IntegerField(blank=True, null=True)),
                ('ch_total', models.IntegerField(blank=True, null=True)),
                ('residente', models.CharField(max_length=3)),
                ('preceptor', models.CharField(max_length=3)),
                ('desligamento', models.CharField(max_length=3)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.profissional')),
            ],
        ),
    ]
